# Generated by Django 4.0.5 on 2022-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(max_length=100, verbose_name='Мое имя')),
                ('myNumber', models.CharField(max_length=12, verbose_name='Мой номер')),
                ('myPhoto', models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/profile/', verbose_name='Мое фото')),
                ('myDescription', models.TextField(verbose_name='Мое описание')),
                ('myGmail', models.EmailField(max_length=254, verbose_name='Гугл почта')),
                ('myYandexMail', models.EmailField(max_length=254, verbose_name='Яндекс почта')),
                ('myVK', models.URLField(verbose_name='VK')),
                ('myInstagram', models.URLField(verbose_name='Instagram')),
                ('MyGitHub', models.URLField(verbose_name='Мой ГитХаб')),
                ('myBirthDay', models.DateField(verbose_name='Мой день рождения')),
                ('myEducation', models.CharField(max_length=100, verbose_name='Мое Образование')),
            ],
            options={
                'verbose_name': 'Мой профиль',
                'verbose_name_plural': 'Мои профили',
            },
        ),
    ]
