# Generated by Django 4.0.5 on 2022-07-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateTimeField(verbose_name='Время')),
                ('numberPhoto', models.IntegerField(verbose_name='Количество фотографий')),
                ('photo_1', models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 1')),
                ('someText', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
