# Generated by Django 4.0.5 on 2022-07-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='photo_10',
            field=models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 10'),
        ),
        migrations.AddField(
            model_name='mypost',
            name='photo_2',
            field=models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='mypost',
            name='photo_3',
            field=models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='mypost',
            name='photo_4',
            field=models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='mypost',
            name='photo_5',
            field=models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 5'),
        ),
        migrations.AddField(
            model_name='mypost',
            name='photo_6',
            field=models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 6'),
        ),
        migrations.AddField(
            model_name='mypost',
            name='photo_7',
            field=models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 7'),
        ),
        migrations.AddField(
            model_name='mypost',
            name='photo_8',
            field=models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 8'),
        ),
        migrations.AddField(
            model_name='mypost',
            name='photo_9',
            field=models.ImageField(default='static/userList/Platypus.png', upload_to='uploads/posts/', verbose_name='Фото 9'),
        ),
    ]
