# Generated by Django 4.0.5 on 2022-08-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mypost_photo_10_mypost_photo_2_mypost_photo_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='photo_1',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_10',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 10'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_2',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_3',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_4',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_5',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_6',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 6'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_7',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 7'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_8',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 8'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_9',
            field=models.URLField(default='https://psv4.userapi.com/c536236/u240514110/docs/d7/e6002448a5a1/Platypus.png?extra=3kj7j47V1IJwlfpurBOiY03oCvrGiGEs3numdSZvXHje4m03UDgzQfGyJ3Xox6Ma_YenUS-DdKdovaXyaTMGPvMHROgXQs1jEHhXLT81VG-WYKtvy_yyXC2SyJlLqL7eX9UaODc0oI1Nmxp2me0z3L_C0A', verbose_name='Фото 9'),
        ),
    ]
