# Generated by Django 4.0.6 on 2022-08-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mypost_photo_1_alter_mypost_photo_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='photo_1',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_10',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 10'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_2',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_3',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_4',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_5',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_6',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 6'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_7',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 7'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_8',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 8'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='photo_9',
            field=models.URLField(default='http://drive.google.com/uc?export=view&id=', verbose_name='Фото 9'),
        ),
    ]
